export const ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint8',
        name: 'activityType',
        type: 'uint8',
      },
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'activityId',
        type: 'bytes32',
      },
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      {
        indexed: false,
        internalType: 'uint32',
        name: 'timestamp',
        type: 'uint32',
      },
    ],
    name: 'ActivityStored',
    type: 'event',
  },
  {
    inputs: [],
    name: 'ACTIVITY_TYPE_BIKE',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ACTIVITY_TYPE_RUN',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ACTIVITY_TYPE_SWIM',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'PROTOCOL_VERSION',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'activities',
    outputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint8', name: 'version', type: 'uint8' },
      { internalType: 'uint32', name: 'timestamp', type: 'uint32' },
      { internalType: 'uint8', name: 'activityType', type: 'uint8' },
      { internalType: 'uint32', name: 'duration', type: 'uint32' },
      { internalType: 'bytes32', name: 'fileId', type: 'bytes32' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'activitiyId', type: 'bytes32' }],
    name: 'getActivity',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'uint8', name: 'version', type: 'uint8' },
          { internalType: 'uint32', name: 'timestamp', type: 'uint32' },
          { internalType: 'uint8', name: 'activityType', type: 'uint8' },
          { internalType: 'uint32', name: 'duration', type: 'uint32' },
          { internalType: 'bytes32', name: 'fileId', type: 'bytes32' },
        ],
        internalType: 'struct OpenTrainingDataProtocol.Activity',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getUserActivities',
    outputs: [{ internalType: 'bytes32[]', name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint8', name: 'activityType', type: 'uint8' },
      { internalType: 'bytes32', name: 'fileId', type: 'bytes32' },
      { internalType: 'uint32', name: 'timestamp', type: 'uint32' },
      { internalType: 'uint16', name: 'duration', type: 'uint16' },
    ],
    name: 'storeActivity',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userActivities',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'userActivityCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
